name: Tailscale Linux RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Install XFCE Desktop & VNC
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver
          
      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1280x720 -depth 24
          
